buddy/urls.py
from django.urls import path, re_path
from . import views

app_name = 'buddy'
urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^(?P<poo>[^$]+)/(?P<var>[0-9]+)$', views.detail, name='detail'),
    re_path(r'^(?P<poo>[^$]+)/(?P<var>[0-9]+)/favorites$', views.favorites, name='favorites'),
]

buddy/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=300)
    album_title = models.CharField(max_length=3000)
    genre = models.CharField(max_length=300)
    album_logo = models.CharField(max_length=3000)

    def __str__(self):
        return self.artist + ' · ' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=300)
    song_title = models.CharField(max_length=300)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

buddy/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Album, Song


def buddymainredirect(request):
    return redirect('/buddy')


def index(request):
    all_albums = Album.objects.all()
    all_songs = Song.objects.all()
    context = {
        'all_albums': all_albums,
        'all_songs': all_songs,
    }
    return render(request, 'buddy/index.html', context)


def detail(request, poo, var):
    spooge = get_object_or_404(Album, pk=var)
    return render(request, 'buddy/detail.html', {
        'var_album': spooge,
        'var_artist': poo,
    })


def favorites(request, poo, var):
    spooge = get_object_or_404(Album, pk=var)
    try:
        buddyssong = spooge.song_set.get(pk=request.POST['da song'])
    except (KeyError, Song.DoesNotExist):
        return render(request, 'buddy/detail.html', {
            'var_album': spooge,
            'errr_message': "you fuck up bitch! you lost?"
        })
    else:
        buddyssong.is_favorite = True
        buddyssong.save()
        return render(request, 'buddy/detail.html', {
            'var_album': spooge,
            'var_artist': poo,
        })

buddy/templates/buddy/detail.html
<a href="/buddy/">home</a><br><br>
<img src="{{ var_album.album_logo }}">

<h1>{{ var_album.album_title }}</h1>
<div><h2>{{ var_album.artist }}</h2></div>

{% if errr_message %}
    <p><strong>{{ errr_message }}</strong></p>
{% endif %}

<form action="{% url 'buddy:favorites' var_artist var_album.id %}" method="post">
    {% csrf_token %}
    {% for s in var_album.song_set.all %}
        <input type="checkbox" id="s{{ forloop.counter }}" name="da song" value="{{ s.id }}" />
        <label for="s{{ forloop.counter }}" >
            {{ s.song_title }}
            {% if s.is_favorite %}
                <img src="http://i.imgur.com/b9b13Rd.png" />
            {% endif %}
        </label><br>
    {% endfor %}
    <input type="submit" value="buddy's favorite songs"/>
</form>

buddy/templates/buddy/index.html
    {% if all_albums %}
        <ul>
            {% for i in all_albums %}
            <li><a href="{% url 'buddy:detail' poo=i.artist var=i.id %}">{{ i.album_title }}</a></li>
            {% if i.id == 3 %}
                <p>wow! {{ i.genre }} music is cool and this is the 3rd one!!</p>
            {% endif %}
        {% endfor %}
    </ul>
    {% else %}
        <h4>sucks you don't got shit bitch!!</h4>
    {% endif %}